name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # renovate: datasource=docker depName=docker.io/multiarch/qemu-user-static versioning=regex:^(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)-(?<build>\\d+)$
  QEMU_VERSION: 7.0.0-7
  # renovate: datasource=docker depName=docker.io/buildpack-deps versioning=ubuntu
  BUILDPACK_DEPS_VERSION: '20.04'

jobs:
  build-and-test-multi-arch:
    name: Test on ${{ matrix.arch }}
    runs-on: ubuntu-latest
    # Run steps on a matrix of 2 arch.
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      if: ${{ steps.skip-check.outputs.should_skip != 'true' }}

    - name: Set up Go
      uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # tag=v3.2.1
      with:
        go-version-file: .go-version
        check-latest: true
        cache: true

    - name: Test
      if: ${{ matrix.arch == 'amd64' }}
      run: |
        go test -race ./...

    - name: 'Run ${{ matrix.arch }}'
      if: ${{ matrix.arch != 'amd64' }}
      run: |
        # Register QEMU
        docker run --rm --privileged "docker.io/multiarch/qemu-user-static:${QEMU_VERSION}" --reset -p yes

        # Run platform specific based buildpack-deps image. Run it as a daemon in the background.
        # Sleep the container for 1 day so that it keeps running until
        # other steps are completed and the steps below can use the same container.
        docker run \
          --name=buildpack-deps \
          --detach \
          --platform 'linux/${{ matrix.arch }}' \
          --volume /home/runner/work:/home/runner/work \
          --workdir "${PWD}" \
          "docker.io/buildpack-deps:${BUILDPACK_DEPS_VERSION}" \
          bash -c 'uname -m && sleep 1d'

    # Install Golang, which will be used to build the code.
    - name: 'Setup Go on ${{ matrix.arch }}'
      if: ${{ matrix.arch != 'amd64' }}
      shell: docker exec buildpack-deps bash -e {0}
      run: |
        GO_VERSION="$(<.go-version)"
        wget --directory-prefix=/tmp "https://dl.google.com/go/go${GO_VERSION}.linux-${{ matrix.arch }}.tar.gz"
        tar -C /usr/local/ -xzf "/tmp/go${GO_VERSION}.linux-${{ matrix.arch }}.tar.gz"
        export PATH="${PATH}:/usr/local/go/bin"
        go version

    # Run Go Tests. This is a very slow operation on ARM container.
    - name: 'Test on ${{ matrix.arch }}'
      if: ${{ matrix.arch != 'amd64' }}
      shell: docker exec buildpack-deps bash -e {0}
      run: |
        export PATH="${PATH}:/usr/local/go/bin"
        go test -buildvcs=false -v ./...
